# Generated by Django 2.0.5 on 2019-07-05 12:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAccountData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('contact_no', models.IntegerField()),
                ('describe_yourself', models.CharField(max_length=50)),
                ('Choose_a_profile_picture', models.ImageField(upload_to='')),
                ('what_are_you_in_interested', models.CharField(max_length=50)),
                ('Preferred_Languages', multiselectfield.db.fields.MultiSelectField(choices=[('Eng', 'English'), ('Tel', 'Telugu'), ('Hin', 'Hindi'), ('Kan', 'Kannada')], max_length=150)),
            ],
        ),
    ]
