# Generated by Django 2.0.5 on 2019-07-06 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitterapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateAccountData',
            new_name='AccountData',
        ),
    ]
