# Generated by Django 2.0.5 on 2019-07-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwitterapp', '0002_auto_20190706_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='test2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='accountdata',
            old_name='username',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='accountdata',
            name='describe_yourself',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accountdata',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accountdata',
            name='what_are_you_in_interested',
            field=models.CharField(max_length=100),
        ),
    ]
