# Generated by Django 2.0.5 on 2019-07-06 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dwitterapp', '0003_auto_20190706_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountData',
            new_name='Account',
        ),
    ]
